### ISSUE TITLE
Hero y Header 

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/AI-CHANGE.io#2]
- [x] Desarrollar hero y header para "How AI will...", esto implica los archivos que se requieren, HTML Y CSS que se requiera.
- [x] Realizar Rama hero
- [x] Hacer commit.
- [x] Crear pull request.

**Comment by Fernando7Josue** [comment]
fixes: #8  

1. Se realizo el html, css del header y hero
2. Se agregaron las imágenes
3. Se realizo la rama correspondiente
4. Se hizo el commit y pull request
