### ISSUE TITLE
Our recent post

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/AI-CHANGE.io#3]
- [x] Maquetar el contenido de "our recent post" utilizando boostrap, incluyendo archivos necesarios como imagenes, HTML o CSS si es necesario
- [x] Crear una rama para subir el archivo y hacer commit.
- [x] Hacer un pull request al main.

**Comment by Fernando7Josue** [comment]
fixes: #9 

1. Se realizo el html y css de Our Recent Post
2. Se agregaron las imágenes
3. Se realizo el commit y pull request
