### ISSUE TITLE
Popular post

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/AI-CHANGE.io#4]
- [x] Realizar el maquetado del contenido de "popular post", utilizando boostrap, subiendo archivos que se requieren, HTML Y CSS si es necesario.
- [x] Hacer una rama para subir el trabajo.
- [x] Hacer un commit.
- [x] Crear un pull request al main.

**Comment by LuisAmir04** [comment]
https://github.com/MacRoberto/AI-CHANGE/pull/10
![image](https://github.com/user-attachments/assets/f72c566d-8aff-4f5f-a3cf-2dafee9490ee)
Se maquetó correctamente el apartado popular post y se cerró el pull request
