### ISSUE TITLE
Footer How AI will change the future

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/AI-CHANGE.io#5]
- [x] Realizar maquetado correspondiente al footer de "How AI will change the future" 
- [x] Crear una rama nueva para subir los archivos que fueron necesarios.
- [x] Hacer commit a la rama creada.
- [x] Hacer pull request al main del trabajo realizado.

**Comment by LuisAmir04** [comment]
https://github.com/MacRoberto/AI-CHANGE/pull/11
Se cerró correctamente el pull request del maquetado del apartado footer

- [x] Se añadió una barra para agregar correos
- [x] Se añadió Iconos de redes sociales
- [x] Se añadió un apartado de copyright

![image](https://github.com/user-attachments/assets/19dca664-d075-434b-bcb0-8c25b9e65c4c)
