### ISSUE TITLE
Find our all blogs from here 

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/AI-CHANGE.io#6]
Hacer el maquetado del Page correspondiente al "Find our all blogs from here" Usando boostrap y archivos que se requieren. Esto incluye hacer los siguientes puntos:

- [x] Header 
- [x] Body page (contenido de la página)
- [x] Footer
- [x] Crear una rama nueva para subir el trabajo 
- [x] hacer commit a la rama nueva
- [x] Hacer un pull request al main del trabajo

Note: 
The assignees to Macroberto is for inspection

**Comment by Emiliano-dev25052** [comment]
Se completo el issue en el pull request vinculado
