### ISSUE TITLE
How to make a Game 

### ISSUE THREAD

**Issue by MacRoberto** [MacRoberto/AI-CHANGE.io#7]
Realizar el page de "How to make a Game look more attractive with New VR & AI Technology", se debe utilizar boostrap durante el desarrollo. Este page incluye hacer los siguientes puntos:

- [x] Header
- [x] Body page (contenido de la pagina a maquetar).
- [x] Footer
- [x] Crea una rama para subir el archivo
- [x] Hacer commit a esta rama nueva del trabajo hecho
- [x] Hecer un pull request al main.

Note:
The assignees Macroberto is going to review the work.

**Comment by JJS74** [comment]
Fixes #5 

- [x] Se realizo el header para esta pantalla
- [x] Se realizo su contenido
- [x] Se realizo footer
- [x] La rama referente a esta asignación fue creada
- [x] El commit se ha enviado
- [x] Un pullrequest también fue realizado

![Image](https://github.com/user-attachments/assets/32fbf8ef-decd-474b-8703-0c52b207aaf9)
![Image](https://github.com/user-attachments/assets/0245fec4-dbe1-456e-90dd-92811a2029f6)
![Image](https://github.com/user-attachments/assets/e2029a81-bef8-488f-9ffd-e9288635cbda)
![Image](https://github.com/user-attachments/assets/c0d60948-99f7-4ff0-8b88-a5af02d003b3)
